services:
  routeros:
    image: evilfreelancer/docker-routeros:latest
    container_name: mikrotik-test
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
      - /dev/kvm
    ports:
      # - "2222:22"      # SSH
      # - "2223:23"      # Telnet
      - "80:80"        # Webfig
      - "8291:8291"    # Winbox 
      - "8728:8728"    # API
      - "8729:8729"    # API-SSL
    volumes:
      - routeros-data:/data
    networks:
      - default
      - routeros_net  


  vpn:
    image: softethervpn/vpnserver:latest
    container_name: vpn-test
    cap_add:
      - NET_ADMIN
    ports:
      - "443:443/tcp"
      - "5555:5555/tcp"
    environment:
      - SPW=admin123  
    restart: always
    networks:
      - default
      - routeros_net  



networks:
  routeros_net:
    driver: bridge

volumes:
  routeros-data:
