# Generated by Django 6.0.3 on 2026-04-07 12:00

import app.commone.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('microtiks', '0003_subscriptioncategorie_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GainSysteme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default=app.commone.models.generate_slug, max_length=40, unique=True)),
                ('created_at', models.DateField(auto_now=True)),
                ('update_at', models.DateField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('microtik', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gain_microtik', to='microtiks.microtik')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Windraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default=app.commone.models.generate_slug, max_length=40, unique=True)),
                ('created_at', models.DateField(auto_now=True)),
                ('update_at', models.DateField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phone_number', models.CharField(max_length=10)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('microtik', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='windraw_microtik', to='microtiks.microtik')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_windraw', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
