# Generated by Django 6.0.3 on 2026-03-30 16:02

import app.users.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=10)),
                ('user_type', models.CharField(choices=[('admin', 'admin'), ('ownermicrotik', 'owner microtik')], default='ownermicrotik', max_length=20)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', app.users.managers.UserManager()),
            ],
        ),
    ]
