# Generated by Django 6.0.3 on 2026-04-07 12:00

import app.commone.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_date_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerMicrotik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default=app.commone.models.generate_slug, max_length=40, unique=True)),
                ('created_at', models.DateField(auto_now=True)),
                ('update_at', models.DateField(auto_now_add=True)),
                ('pourcentage', models.IntegerField(default=20)),
                ('carte', models.ImageField(upload_to='carte/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ownermicrotik', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
