# Generated by Django 6.0.3 on 2026-04-02 09:46

import app.commone.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('microtiks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default=app.commone.models.generate_slug, max_length=40, unique=True)),
                ('created_at', models.DateField(auto_now=True)),
                ('update_at', models.DateField(auto_now_add=True)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('code_username', models.CharField(max_length=50)),
                ('code_password', models.CharField(max_length=50)),
                ('limit_uptime', models.CharField(max_length=50)),
                ('profil_name', models.CharField(max_length=50)),
                ('status', models.BooleanField(choices=[('disable', 'Desactiver'), ('active', 'Activer le compte')], default='active')),
                ('microtik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', related_query_name='clients', to='microtiks.microtik')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InfoDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default=app.commone.models.generate_slug, max_length=40, unique=True)),
                ('created_at', models.DateField(auto_now=True)),
                ('update_at', models.DateField(auto_now_add=True)),
                ('phone_number', models.CharField(max_length=10)),
                ('number_receve_code', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='pending', max_length=15)),
                ('profil_name', models.CharField(max_length=50)),
                ('limit_uptime', models.CharField(max_length=50)),
                ('eventId', models.CharField(max_length=250)),
                ('paymentMethod', models.CharField(max_length=20)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('microtik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_deposit', related_query_name='info_deposit', to='microtiks.microtik')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
