# Generated by Django 6.0.3 on 2026-04-07 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infodeposit',
            name='client',
        ),
        migrations.AddField(
            model_name='client',
            name='generate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='info_deposit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='client_deposit', to='clients.infodeposit'),
            preserve_default=False,
        ),
    ]
