# Generated by Django 6.0.3 on 2026-04-10 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_remove_infodeposit_client_client_generate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='generate',
            field=models.CharField(choices=[('systeme', 'generer par le systeme'), ('owner', 'generer par le owner'), ('import', 'importer par csv')], default='systeme', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='info_deposit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_deposit', to='clients.infodeposit'),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('disable', 'Desactiver'), ('active', 'Activer le compte')], default='active', max_length=50),
        ),
    ]
