# Generated by Django 6.0.3 on 2026-04-10 13:06

import app.commone.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionCategorieVpn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default=app.commone.models.generate_slug, max_length=40, unique=True)),
                ('created_at', models.DateField(auto_now=True)),
                ('update_at', models.DateField(auto_now_add=True)),
                ('name', models.CharField(choices=[('mensuel', 'Mensuel'), ('trimestriel', 'Trimestriel'), ('annuel', 'Annuel')], default='mensuel', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, help_text="Prix de l'abonnement", max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubscriptionVpn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default=app.commone.models.generate_slug, max_length=40, unique=True)),
                ('created_at', models.DateField(auto_now=True)),
                ('update_at', models.DateField(auto_now_add=True)),
                ('vpn_username', models.CharField(max_length=50, null=True, unique=True)),
                ('vpn_password', models.CharField(max_length=50, null=True)),
                ('vpn_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('expire_at', models.DateField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.subscriptioncategorievpn')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='SubscribVpn',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='category',
        ),
    ]
