# Generated by Django 6.0.3 on 2026-04-10 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microtiks', '0006_alter_microtik_subscription'),
        ('subscriptions', '0002_subscriptioncategorievpn_subscriptionvpn_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.DeleteModel(
            name='SubscriptionCategorie',
        ),
    ]
