# Generated by Django 6.0.3 on 2026-04-02 09:46

import app.commone.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Microtik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default=app.commone.models.generate_slug, max_length=40, unique=True)),
                ('created_at', models.DateField(auto_now=True)),
                ('update_at', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('ip', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('sold', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('users', models.BigIntegerField(default=0)),
                ('status', models.CharField(default='active', max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='microtiks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default=app.commone.models.generate_slug, max_length=40, unique=True)),
                ('created_at', models.DateField(auto_now=True)),
                ('update_at', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('rate_limit', models.CharField(choices=[('256k/512k', 'Bronze (256k / 512k)'), ('512k/1M', 'Bronze Plus (512k / 1M)'), ('1M/2M', 'Silver (1M / 2M)'), ('2M/4M', 'Silver Plus (2M / 4M)'), ('4M/8M', 'Gold (4M / 8M)'), ('5M/10M', 'Gold Plus (5M / 10M)'), ('10M/20M', 'Platinum (10M / 20M)'), ('20M/50M', 'Ultra (20M / 50M)'), ('50M/100M', 'Business (50M / 100M)'), ('0/0', 'Illimité (No Limit)')], default='1M/2M', max_length=20)),
                ('shared_users', models.IntegerField(choices=[(1, '1 Utilisateur (Solo)'), (2, '2 Utilisateurs (Duo)'), (3, '3 Utilisateurs (Famille)'), (5, '5 Utilisateurs (Petit Bureau)'), (0, 'Illimité (Non recommandé)')], default=1)),
                ('session_timeout', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('gnf', 'Franc Guinnen')], default='gnf', max_length=10)),
                ('status', models.CharField(default='active', max_length=50)),
                ('microtik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profils', related_query_name='profils', to='microtiks.microtik')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
