# Generated by Django 6.0.3 on 2026-04-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microtiks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='microtik',
            name='admin_blocked',
            field=models.CharField(default='active', max_length=50),
        ),
    ]
