# Generated by Django 6.0.3 on 2026-04-07 12:00

import app.commone.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microtiks', '0002_microtik_admin_blocked'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default=app.commone.models.generate_slug, max_length=40, unique=True)),
                ('created_at', models.DateField(auto_now=True)),
                ('update_at', models.DateField(auto_now_add=True)),
                ('name', models.CharField(default='pourcentage', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default=app.commone.models.generate_slug, max_length=40, unique=True)),
                ('created_at', models.DateField(auto_now=True)),
                ('update_at', models.DateField(auto_now_add=True)),
                ('expire_at', models.DateField(blank=True, null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='microtiks.subscriptioncategorie')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
