# Generated by Django 6.0.3 on 2026-04-08 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microtiks', '0003_subscriptioncategorie_subscription'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='microtik',
            old_name='users',
            new_name='users_count',
        ),
        migrations.RemoveField(
            model_name='microtik',
            name='description',
        ),
        migrations.RemoveField(
            model_name='microtik',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='microtik',
            name='password',
        ),
        migrations.RemoveField(
            model_name='microtik',
            name='sold',
        ),
        migrations.RemoveField(
            model_name='microtik',
            name='status',
        ),
        migrations.RemoveField(
            model_name='microtik',
            name='username',
        ),
        migrations.AddField(
            model_name='microtik',
            name='is_online',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='microtik',
            name='subscription',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.subscription'),
        ),
        migrations.AddField(
            model_name='microtik',
            name='vpn_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='microtik',
            name='vpn_password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='microtik',
            name='vpn_username',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='microtik',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='microtik',
            name='admin_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.DeleteModel(
            name='SubscriptionCategorie',
        ),
    ]
