# Generated by Django 6.0.3 on 2026-04-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microtiks', '0004_rename_users_microtik_users_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='microtik',
            name='vpn_ip',
        ),
        migrations.RemoveField(
            model_name='microtik',
            name='vpn_password',
        ),
        migrations.RemoveField(
            model_name='microtik',
            name='vpn_username',
        ),
        migrations.AddField(
            model_name='microtik',
            name='commission_rate',
            field=models.FloatField(default=15.0, help_text='Pourcentage prélevé sur les ventes'),
        ),
    ]
