# Generated by Django 6.0.3 on 2026-04-10 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microtiks', '0005_remove_microtik_vpn_ip_remove_microtik_vpn_password_and_more'),
        ('subscriptions', '0002_subscriptioncategorievpn_subscriptionvpn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microtik',
            name='subscription',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suscription_vpn', to='subscriptions.subscriptionvpn'),
        ),
    ]
